version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1160:5000
    env_file:
      - ./.env.dev
